---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: argo-app-default
  source:
    helm:
      parameters:
        - name: image.name
          value: IMAGE_NAME
        - name: image.tag
          value: IMAGE_TAG
    chart: default
    repoURL: https://redhat-developer.github.io/redhat-helm-charts
    targetRevision: 0.0.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
